name: WorldRegions
description: Add more flags and features to WorldGuard regions.
author: Wolflink289
website: http://dev.bukkit.org/server-mods/worldregions/

version: 1.0.0
main: com.wolflink289.bukkit.worldregions.WorldRegionsPlugin

depend: [WorldGuard]
softdepend: [ProtocolLib]

permissions:
    worldguard.region.flag.flags.pve:
        description: The player will not be allowed to attack mobs in no-PvE areas.
        default: not op
    worldguard.region.flag.flags.mob-targeting:
        description: Mobs will not be allowed to attack the player in no-targeting areas.
        default: true
    worldguard.region.flag.flags.hunger:
        description: The player's hunger will not decrease in no-hunger areas.
        default: true
    worldguard.region.flag.flags.regen:
        description: The player will not regenerate health due to a full hunger bar in no-regen areas.
        default: not op
    worldguard.region.flag.flags.healing:
        description: The player will not be able to heal at all in no-healing areas.
        default: not op
    worldguard.region.flag.flags.apply-potion:
        description: The player will receive potion effects in apply-potion areas.
        default: true